export const categories = [
  "الخيال",
  "غير الخيال",
  "العلوم",
  "التكنولوجيا",
  "التاريخ",
  "السيرة الذاتية",
  "الغموض",
  "الرومانسية",
  "الفانتازيا",
  "تطوير الذات",
];

export const books = [
  {
    id: 1,
    title: "غاتسبي العظيم",
    author: "ف. سكوت فيتزجيرالد",
    category: "خيال",
    description:
      "رواية أمريكية كلاسيكية تدور أحداثها في عصر الجاز، تستكشف موضوعات الثروة والحب والحلم الأمريكي من خلال عيني الراوي نيك كاراواي وهو يراقب القصة المأساوية لجاي غاتسبي.",
    cover: "/great-gatsby-book-cover.png",
    available: true,
    isbn: "978-0-7432-7356-5",
    publishedYear: 1925,
    pages: 180,
  },
  {
    id: 2,
    title: "لتقتل طائراً محاكياً",
    author: "هاربر لي",
    category: "خيال",
    description:
      "حكاية مؤثرة عن الظلم العنصري وبراءة الطفولة في الجنوب الأمريكي، تُروى من خلال عيني سكاوت فينش بينما يدافع والدها عن رجل أسود متهم زوراً بالاغتصاب.",
    cover: "/to-kill-a-mockingbird-cover.png",
    available: true,
    isbn: "978-0-06-112008-4",
    publishedYear: 1960,
    pages: 324,
  },
  {
    id: 3,
    title: "1984",
    author: "جورج أورويل",
    category: "خيال",
    description:
      "رواية خيال علمي ديستوبية عن السيطرة الشمولية والمراقبة، تتبع صراع وينستون سميث ضد النظام القمعي للأخ الأكبر في أوقيانيا.",
    cover: "/1984-book-cover.png",
    available: false,
    isbn: "978-0-452-28423-4",
    publishedYear: 1949,
    pages: 328,
  },
  {
    id: 4,
    title: "الحارس في حقل الشوفان",
    author: "ج.د. سالينجر",
    category: "خيال",
    description:
      "رواية مثيرة للجدل حول التمرد المراهق والاغتراب في أمريكا ما بعد الحرب، يرويها هولدن كولفيلد الساخر والمضطرب أثناء تجواله في مدينة نيويورك.",
    cover: "/catcher-in-the-rye-cover.png",
    available: true,
    isbn: "978-0-316-76948-0",
    publishedYear: 1951,
    pages: 277,
  },
  {
    id: 5,
    title: "كبرياء وتحامل",
    author: "جين أوستن",
    category: "رومانسي",
    description:
      "رواية رومانسية عن الآداب والتربية والأخلاق والزواج في إنجلترا الجورجية، تركز على العلاقة المتطورة بين إليزابيث بينيت والمتكبر السيد دارسي.",
    cover: "/pride-and-prejudice-cover.png",
    available: true,
    isbn: "978-0-14-143951-8",
    publishedYear: 1813,
    pages: 432,
  },
  {
    id: 6,
    title: "سيد الخواتم",
    author: "ج.ر.ر. تولكين",
    category: "فانتازيا",
    description:
      "رواية فانتازيا ملحمية عالية عن السعي لتدمير الخاتم الواحد وهزيمة اللورد المظلم ساورون، تتبع رحلة فرودو باغينز والزمالة عبر الأرض الوسطى.",
    cover: "/lord-of-the-rings-cover.png",
    available: true,
    isbn: "978-0-544-00341-5",
    publishedYear: 1954,
    pages: 1216,
  },
  {
    id: 7,
    title: "العاقل",
    author: "يوفال نوح هراري",
    category: "غير روائي",
    description:
      "تاريخ موجز للبشرية، يستكشف كيف هيمن الإنسان العاقل على العالم من خلال الثورات المعرفية والزراعية والعلمية التي شكلت الحضارة الإنسانية.",
    cover: "/placeholder-9sgeo.png",
    available: true,
    isbn: "978-0-06-231609-7",
    publishedYear: 2011,
    pages: 443,
  },
  {
    id: 8,
    title: "الشركة الناشئة الرشيقة",
    author: "إريك ريس",
    category: "تقنية",
    description:
      "منهجية لتطوير الأعمال والمنتجات من خلال التعلم المُتحقق منه والتجريب، تعلم رجال الأعمال كيفية بناء شركات مستدامة في بيئات غير مؤكدة.",
    cover: "/lean-startup-cover.png",
    available: false,
    isbn: "978-0-307-88789-4",
    publishedYear: 2011,
    pages: 336,
  },
  {
    id: 9,
    title: "ستيف جوبز",
    author: "والتر إيزاكسون",
    category: "سيرة ذاتية",
    description:
      "السيرة الذاتية الحصرية لمؤسس شركة آبل ستيف جوبز، مبنية على مقابلات مكثفة، تكشف الشخصية المعقدة وراء واحد من أكثر العقول إبداعاً في التكنولوجيا.",
    cover: "/placeholder-kh4cb.png",
    available: true,
    isbn: "978-1-4516-4853-9",
    publishedYear: 2011,
    pages: 656,
  },
  {
    id: 10,
    title: "الفتاة ذات وشم التنين",
    author: "ستيغ لارسون",
    category: "غموض",
    description:
      "إثارة نفسية حول صحفي وقرصان يحققان في أسرار عائلة ثرية المظلمة، يكشفان الفساد والعنف والقتل في المجتمع السويدي.",
    cover: "/placeholder-odz77.png",
    available: true,
    isbn: "978-0-307-45454-1",
    publishedYear: 2005,
    pages: 672,
  },
  {
    id: 11,
    title: "العادات الذرية",
    author: "جيمس كلير",
    category: "تطوير ذاتي",
    description:
      "دليل عملي لبناء عادات جيدة وكسر العادات السيئة من خلال تغييرات صغيرة ومتدرجة، يوضح كيف يمكن للتحسينات الطفيفة أن تؤدي إلى نتائج رائعة مع الوقت.",
    cover: "/placeholder-7w4mt.png",
    available: true,
    isbn: "978-0-7352-1129-2",
    publishedYear: 2018,
    pages: 320,
  },
  {
    id: 12,
    title: "تاريخ موجز للزمن",
    author: "ستيفن هوكينغ",
    category: "علوم",
    description:
      "مجلد بارز في الكتابة العلمية يستكشف طبيعة الكون ومكاننا فيه، يجعل المفاهيم المعقدة لعلم الكونيات في متناول القراء العامين.",
    cover: "/placeholder-lm2su.png",
    available: true,
    isbn: "978-0-553-38016-3",
    publishedYear: 1988,
    pages: 256,
  },
];

export const users = [
  {
    id: 1,
    name: "Ali Ahmad",
    email: "ali@example.com",
    phone: "+962790000001",
    joinDate: "2022-05-10",
    numberOfBorrowingBooks: 3,
  },
  {
    id: 2,
    name: "Sara Khalid",
    email: "sara@example.com",
    phone: "+962790000002",
    joinDate: "2023-01-22",
    numberOfBorrowingBooks: 5,
  },
  {
    id: 3,
    name: "Omar Naser",
    email: "omar@example.com",
    phone: "+962790000003",
    joinDate: "2021-09-15",
    numberOfBorrowingBooks: 1,
  },
];

export const borrowingManagement = [
  {
    id: 1,
    bookId: 101,
    bookName: "The Silent Patient",
    userId: 501,
    userName: "Ahmed Ali",
    dateBorrowed: "2025-10-10",
    returnDueDate: "2025-10-17",
    actualReturnDate: "2025-10-16",
    state: "returned",
  },
  {
    id: 2,
    bookId: 102,
    bookName: "Atomic Habits",
    userId: 502,
    userName: "Sara Youssef",
    dateBorrowed: "2025-10-15",
    returnDueDate: "2025-10-22",
    actualReturnDate: null,
    state: "borrowing",
  },
  {
    id: 3,
    bookId: 103,
    bookName: "The Alchemist",
    userId: 503,
    userName: "Omar Hassan",
    dateBorrowed: "2025-09-25",
    returnDueDate: "2025-10-02",
    actualReturnDate: null,
    state: "late",
  },
];
